# Generated by Django 2.2.3 on 2019-09-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190903_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_favourite',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
